### ISSUE TITLE
Link https://clayui.com/docs/components causes 404

### ISSUE THREAD

**Issue by chrberndt** [liferay/clay#1180]
The link https://clayui.com/docs/components  used at the end of ttps://clayui.com/docs/getting-started/introduction.html causes a 404 error.

**Comment by matuzalemsteles** [comment]
hey @chrberndt, Thanks for the report, as soon as we send #1111, it will fix these redirect problems. Thanks a lot!

**Comment by chrberndt** [comment]
@matuzalemsteles The issue is closed, but the link https://clayui.com/docs/components still returns 404.

**Comment by matuzalemsteles** [comment]
hey @chrberndt, It looks like it's only fixed in the development environment, thank you very much for that. Thanks!

**Comment by chrberndt** [comment]
If you go to https://clayui.com/docs/components go still get a 404

**Comment by matuzalemsteles** [comment]
hey @chrberndt, we have not yet deployed to clayui.com, sorry for that.

**Comment by chrberndt** [comment]
hey @matuzalemsteles , any plans to do so in the foreseeable future? ;-)

**Comment by matuzalemsteles** [comment]
We will be deploying today. 🙂
